### ISSUE TITLE
Setting "on" for ending causes error

### ISSUE THREAD

**Issue by jamesfulford** [jamesfulford/cashflow-projector#67]
- for some reason, changing Ending "on" (the `until` field) causes the Python interpreter to get upset about tz-aware timestamps for dtstart and UNTIL not being in UTC.

```
Traceback (most recent call last):
  File "/home/pyodide/engine/recur.py", line 37, in generate_event_transactions
    dates = get_dates(rule, context.parameters)
  File "/home/pyodide/engine/recur.py", line 20, in get_dates
    rule_generator = iter(rrulestr(rule["rule"], dtstart=start))
  File "/lib/python3.10/site-packages/dateutil/rrule.py", line 1732, in __call__
    return self._parse_rfc(s, **kwargs)
  File "/lib/python3.10/site-packages/dateutil/rrule.py", line 1652, in _parse_rfc
    return self._parse_rfc_rrule(lines[0], cache=cache,
  File "/lib/python3.10/site-packages/dateutil/rrule.py", line 1561, in _parse_rfc_rrule
    return rrule(dtstart=dtstart, cache=cache, **rrkwargs)
  File "/lib/python3.10/site-packages/dateutil/rrule.py", line 470, in __init__
    raise ValueError(
ValueError: RRULE UNTIL values must be specified in UTC when DTSTART is timezone-aware

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pyodide/engine/pyodide.py", line 34, in process_daybydays
    daybydays = generate_daybydays(context)
  File "/home/pyodide/engine/daybydays.py", line 26, in generate_daybydays
    transactions = get_transactions_up_to(context)
  File "/home/pyodide/engine/generate_instances.py", line 12, in get_transactions_up_to
    all_transactions = generate_event_transactions(context)
  File "/home/pyodide/engine/recur.py", line 52, in generate_event_transactions
    assert False, f"Rule `{rule_id}` is an invalid rrule per RFC 5545"
AssertionError: Rule `1706055664643` is an invalid rrule per RFC 5545
```

- for some reason, this occurs because while editing a rule, we submit for Python backend processing. What is mutating the values, and what is causing the refresh?

**Comment by jamesfulford** [comment]
The refresh was actually just a delayed re-render having to do with React Query doing 3 tries with space between.

I'm not sure how this wasn't happening before. I've removed "Z" from the end of the UNTIL part of the rrule string, and that resolves the issue.
